

import os
import uuid
from datetime import datetime
from docx import Document

from agent.prompts import SECTION_PROMPT, REFLECTION_PROMPT
from agent.utils import ensure_dir, safe_parse_json, clamp_text


class Executor:

    def __init__(self, llm, output_dir="demo_outputs"):
        self.llm = llm
        self.output_dir = output_dir
        ensure_dir(output_dir)

    def execute_plan(self, plan, user_request):

        sections = []
        execution_log = []
        previous = ""

        document_type = plan.get(
            "document_type",
            "Business Document"
        )

        for step in plan["plan"]:

            tool = step["tool"].lower()

            if tool == "llm":

                prompt = SECTION_PROMPT.format(

                    user_request=user_request,

                    document_type=document_type,

                    previous_sections=previous,

                    section_name=step["name"],

                    task_prompt=step["prompt"]

                )

                response = self.llm.chat(
                    [{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=1200,
                )

                content = response["content"].strip()

                sections.append(
                    {
                        "title": step["name"],
                        "content": content
                    }
                )

                previous += f"\n\n{step['name']}\n{content}"

                execution_log.append(
                    {
                        "step": step["step"],
                        "section": step["name"],
                        "status": "Completed"
                    }
                )

        reflection = self._reflection(sections)

        path = self._create_docx(
            sections,
            plan,
            user_request,
            document_type,
            execution_log
        )

        return {
            "execution_log": execution_log,
            "reflection": reflection,
            "docx_path": path,
        }

    ###################################################

    def _reflection(self, sections):

        text = ""

        for s in sections:
            text += f"{s['title']}\n{s['content']}\n\n"

        prompt = REFLECTION_PROMPT.format(
            document_text=clamp_text(text, 6000)
        )

        try:

            result = self.llm.chat(
                [{"role": "user", "content": prompt}],
                temperature=0,
                force_json=True,
            )

            return safe_parse_json(result["content"])

        except Exception:

            return {"ok": True}

    ###################################################

    def _create_docx(

        self,

        sections,

        plan,

        user_request,

        document_type,

        execution_log

    ):

        filename = f"{uuid.uuid4().hex}.docx"

        path = os.path.join(
            self.output_dir,
            filename
        )

        doc = Document()

        doc.add_heading(document_type, 0)

        doc.add_paragraph(
            f"Generated by Autonomous AI Agent\n"
            f"{datetime.now().strftime('%d %B %Y %H:%M')}"
        )

        doc.add_heading("User Request", 1)

        doc.add_paragraph(user_request)

        assumptions = plan.get(
            "assumptions",
            []
        )

        if assumptions:

            doc.add_heading(
                "Assumptions",
                level=1
            )

            for a in assumptions:
                doc.add_paragraph(
                    a,
                    style="List Bullet"
                )

        tasks = plan.get(
            "tasks",
            []
        )

        if tasks:

            doc.add_heading(
                "Execution Plan",
                level=1
            )

            for t in tasks:
                doc.add_paragraph(
                    t,
                    style="List Number"
                )

        doc.add_page_break()

        for section in sections:

            doc.add_heading(
                section["title"],
                level=1
            )

            doc.add_paragraph(
                section["content"]
            )

        doc.add_page_break()

        doc.add_heading(
            "Execution Summary",
            level=1
        )

        for log in execution_log:

            doc.add_paragraph(

                f"Step {log['step']} : "
                f"{log['section']} : "
                f"{log['status']}",

                style="List Bullet"

            )

        doc.add_heading(
            "Quality Check",
            level=1
        )

        doc.add_paragraph(
            "This document was automatically reviewed by the reflection agent."
        )

        doc.save(path)

        return path